### ISSUE TITLE
For loop with two target variables not supported (to iterate over dict key value pair)

### ISSUE THREAD

**Issue by de-git** [azazel75/metapensiero.pj#19]
The following code results in an error:

> UnsupportedSyntaxError: Node type 'For': ... . Target must be a name, Are you sure is only one?

```python
some_dict = dict()
for key, value in some_dict.items():
  # ...
```

Transcrypt for example is translating this to:
```javascript
for (var [key, value] of some_dict.py_items()) {
  // ...
}
```

An alternative would perhaps be:
```javascript
Object.keys(some_dict).forEach(key => {
  const value = some_dict[key];
  // ...
}
```

**Comment by azazel75** [comment]
Hi

it depends on which kind of dict you are using, but it is actually supported. If you use a normal js Object you can do:

```python
for key in dict(your_object):
    value = your_object[key]
    ....

```

or if you are using Map or WeakMap instances you can better write it like:

```python
for key, value in iterable(your_map):
     ....


```

Please read the docs at https://github.com/azazel75/metapensiero.pj#for-statement before opening bugs.

cheers

**Comment by de-git** [comment]
Thank you for the response.

> Please read the docs at https://github.com/azazel75/metapensiero.pj#for-statement before opening bugs.

I did indeed read the docs before opening the issue.

The examples work but that assumes that the 'Python' code is written in exactly the same way. Perhaps it wasn't clear to me initially from the docs that it is only meant to be written in that way rather than just providing examples.

The example I've given was a valid Python code that isn't that uncommon. Wrapping an existing dict in a new dict for the iteration doesn't seem to be a common Python pattern though. Anyway, I may have misunderstood the purpose of the project. So never mind.

**Comment by azazel75** [comment]
It's because the  design choices I made. This project is different from Transcrypt and other systems like that. They reimplement most of Python's user level data structures, partially shielding you from the need of knowing JavaScript by creating adaptation layers for them. JavaScripthon does not do that, it is a much thinner layer. The object you are interacting with in the code is a plain JS one, nothing more... but nothing less ;-)

About the "dict(var_name)" notation, It's needed to tell the translator to convert your "for" statement into the wanted version of the JS for, it's just a coding shortcut, you can say. You are not the first person that tells me that it may be a  counter-intuitive expression, @lelit told me already.

I'm actually thinking if the new Python type annotations would be a better fit for that, but i've still to come to a decision.

**Comment by azazel75** [comment]
Ah, If you are curious, you can find the actual code that does the translation here: https://github.com/azazel75/metapensiero.pj/blob/master/src/metapensiero/pj/transformations/forloops.py#L77

**Comment by de-git** [comment]
I like that this project targets ES6. What are the use-cases for this project though?

Ideally I just want to get some Python code translated to JavaScript which I could import just like any other JavaScript. This would allow for code sharing. Where possible it would be able to translate best practice Python code as is. Not sure if that was your vision as well.

Perhaps it could use something like your 'in_es6' method where it can't infer the type. (I think my preference would be if 'in_es6' etc. where, perhaps optionally, imported from a ES6 module).

BTW there is also some variable scoping issue in loops which I could raise if you are interested

**Comment by azazel75** [comment]
I'm using it to produce JavaScript code that its used to interface with other JS libraries and it avoids most of the mind context-switching burden while coding both Python and JS code. As I said, while Transcrypt saves you from the knowledge of some JavaScript initially, as soon as you interface your code with other JS library code you will have to take both JavaScript AND Transcrypt into account.

Let's say, for example, that your Python loop is in a function "do_something(options)" which is called by external JS code (where "options" is the "dict" you loop on).  The function is like:

```python

def do_something(options):
    for k, v in options.items():
        print(k, v) # do something better here
```

Transcrypt converts it to something like:
```javascript
var do_something = function (options) {
    var __iterable0__ = options.py_items ();
    for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
        var __left0__ = __iterable0__ [__index0__];
        var k = __left0__ [0];
        var v = __left0__ [1];
        print (k, v);
    }
};
```
Assuming that the external JS code is creating such "options" dict,  to ensure that your loop will not blow in your face using Transcrypt, you are forced to convert your "best practice" Python code to something like:

```python

def do_something(options):
    options = dict(options)
    for k, v in options.items():
        print(k, v) # do something better here
```

This to ensure that the "options" value will have that "py_items()" method defined no matter who calls it. (See https://github.com/QQuick/Transcrypt/blob/4d3cf1fa77aa87a65cd9afb3fff1b38079721cee/transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js#L1294 ) 

So Transcrypt maybe does a better job if  you know nothing about JavaScript and your code does not interface with external JS libraries. Because if it does, you will end up doing "not so pythonic code" anyway. With the notable inconvenience that maybe you have written your code and tests in Python translated to JS and all is doing well, but as soon as you "plug it in" to work with your JS library of preference it will start having issues and you will have an hard day of finding bugs and fixing them, or you will end up rewriting you external JS library in Transcrypt and you will almost die of boredom.

I don't want to do that and i don't want to reinvent the wheel transforming an existent JS library in simil-Python code. I do prefer a more "straight" approach, where the developer is more conscious of the final JS environment where his code will run in the end.

About the "in" and "in_es6" functions in snippets.py, the difference with the dict is that i consider it a core Python semantic, instead what could be a best fit for the "dict" python class in js land is left to the judgement of the developer. Don't need ES6 stuff and your keys are strings? Use the normal JS object class. You want to have instances or integers as keys and you want to use the JS iterator protocol at the possible cost of a possible slow down due to polifills? Use an ES6 instance of Map or WeakMap.

About the variable scoping, i'm interested in any real bug of course :-) . I do not know what are you referring to but beware that var statements in JS are hoisted, so a variable declared in the middle of a function body is available in all the body.

cheers
